pet:
  version: 1
  kind:
    id: 1
    type: str
  age:
    id: 2
    type: float

person:
  version: 1
  name:
    id: 1
    type: str
  age:
    id: 2
    type: int
  is_man:
    id: 3
    type: bool
  height:
    id: 4
    type: float
  pet:
    id: 5
    type: pet
    version: 1
  grades:
    id: 6
    type: int

