pet:
  version: 1
  kind:
    id: 1
    type: str
  age:
    id: 2
    type: float

person:
  version: 1
  name:
    id: 1
    type: str
  age:
    id: 2
    type: int
  is_man:
    id: 3
    type: bool
  height:
    id: 4
    type: float
  pet:
    id: 5
    type: pet
    version: 1
  grades:
    id: 6
    type: list
    element_type: int
  add_data:
    id: 7
    type: dict
    key_type: int
    element_type:
      type: dict
      key_type: str
      element_type:
        type: list
        element_type: int