version: 1
fields_num: 256

pet:
  kind:
    id: 1
    type: str
  age:
    id: 2
    type: float

person:
  name:
    id: 1
    type: str
  age:
    id: 2
    type: int
  is_man:
    id: 3
    type: bool
  height:
    id: 4
    type: float
  pet:
    id: 5
    type: pet
  grades:
    id: 6
    type: int

